### ISSUE TITLE
Thx for making this. Have been looking for a tts solution like this in ubuntu for ages

### ISSUE THREAD

**Issue by distbit0** [gnat/text-to-speech-ubuntu#2]

**Comment by gnat** [comment]
You're welcome! 🙂

**Comment by distbit0** [comment]
https://zenquest.co/team/eben-farnworth/rabbitwhole/text-to-speech-on-linux-ai-rising I found this btw which I have found to be much hgiher quality than espeak ng. Worth checking out! :)

I use: mimic3  --noise-w 0 --noise-scale 0 --length-scale .4 --noise-scale 0  --voice en_US/ljspeech_low  --interactive "$(xclip -selection primary -out)"

**Comment by distbit0** [comment]
https://mycroftai.github.io/mimic3-voices/ see here to listen to other available voices

**Comment by gnat** [comment]
Yeah been playing around with these as well- more natural voices would be nice.

I may replace espeak in this repo if I can get the install instructions down to something super easy. espeak has a lot going for it- you can get it with just `apt install`, there's a windows equivalent, etc.
